### ISSUE TITLE
Parts getting duplicated

### ISSUE THREAD

**Issue by justdave** [gvellut/jncep#12]
I'm not sure what's causing this because it seems to happen at random, but about 2/3rds of the parts I've downloaded with version 26 have duplicated the part content.

![Screenshot_20210611-223532.jpg](https://user-images.githubusercontent.com/307334/121762727-c8daf580-cb05-11eb-97a9-ec637db7a321.jpg)

The cover image has always been in its own "chapter" and it still only happens once.
The part itself winds up twice, as you can see in the chapter list screenshot above. Both chapters have the entire content of the part in them.

I usually discover this when I get to the end of a part and don't realize I'm on the last page, and turn the page and suddenly "hey, I read this already".

**Comment by gvellut** [comment]
Thank you. I will have a look.

I have been using that version as well but I haven't noticed any duplicate content.

Could you send me an EPUB file that exhibits the issue?

**Comment by justdave** [comment]
GitHub won't let me upload epub files, so its on my own site and here's a link to it: https://www.justdave.net/grab/82b1f29838194014561612a0f6205a60.epub

**Comment by gvellut** [comment]
Thank you.

I looked at the file you provided but I don't see any problem of duplicate content either in the Calibre EPUB reader:

<img width="300" alt="Screenshot 2021-06-15 at 11 49 51" src="https://user-images.githubusercontent.com/3685/122033001-6e28ee80-cdd0-11eb-8de2-8ef46d393549.png">

or Apple iBooks:

<img width="500" alt="Screenshot 2021-06-15 at 11 50 02" src="https://user-images.githubusercontent.com/3685/122032975-69fcd100-cdd0-11eb-8c1d-1e7f0ab41d71.png">

I also checked the inside of the EPUB and there is only one part inside.

The EPUB generation code has not changed with version 26 so could it be an issue with the EPUB reader (Moon+ Reader Pro you told me)? Has there been a new version recently?

Possibly, instead of the formal TOC document (toc.ncx), the EPUB reader tries to parse the HTML page with the TOC content (nav.xhtml, but it is just supposed to be displayed to the user as is): This is where both `<h2>Otherside Picnic Volume 5 Part 7</h2>` (with no link though) and a link to the part content with text `Part 7` appear.

**Comment by justdave** [comment]
Yeah, It's Moon+ Reader Pro.  There had been an update to it about a week or two prior, and there's been another update since then, and I haven't seen it again recently.  Although I don't see anything that sounds like that listed in the change log, I suppose it might have been a bug and they fixed it and they just thought it not worth mentioning in the notes.
