### ISSUE TITLE
Fails to run with --parts n:

### ISSUE THREAD

**Issue by shakyr** [gvellut/jncep#21]
For version 36, currently unable to run the command with --parts n: as per the example below.

`jncep epub --output ./books --parts 1: --byvolume --images https://j-novel.club/series/the-great-cleric`

`*** An unrecoverable error occured ***`
`'>=' not supported between instances of 'int' and 'str'`

**Comment by gvellut** [comment]
Thank you for your feedback.

There was indeed a bug. I corrected it and added some unit tests so hopefully every case is covered.

I will make a new release soon (but I want to add an additional feature so it may be a few days) so in the meantime you can use :
- `1.1:`
- or just `:` 
- or even no `--parts` (since you use the series URL)

instead of `1:`  if you want to make it work (I assume you want the whole series).
