### ISSUE TITLE
Can not download the volume i own

### ISSUE THREAD

**Issue by greatlord** [gvellut/jncep#23]
Hi
I own Ascendance of a Bookworm volume 1 all part, it can not download it.

**Comment by gvellut** [comment]
The tool only works with pre-pub novels (including the parts that are always available like the first parts of each volume + monthly catch-ups, if they are available in the current month), not the book you may have otherwise bought,

Currently, for Ascendance of a Bookworm volume 1, only the first part is available so you will not be able to download more than that.

If you run:

```jncep epub https://j-novel.club/series/ascendance-of-a-bookworm#volume-1```

Only the first part `Ascendance_of_a_Bookworm_Part_1_Volume_1_Part_1.epub` will be downloaded.

**Comment by greatlord** [comment]
OK thanks for you expain is it not posible to add to download the part you own as well ??

**Comment by gvellut** [comment]
No. It is not something I use, so I will not add that functionality. 

If you search the forums, there is a reference to a tool to download the books you have bought explicitly: https://forums.j-novel.club/topic/1603/download-tool-for-your-jnc-library

I have never used it and I am not the maintainer, so  have no idea if it still works with the recent changes of the J-Novel Club API (you can use that post from the forum to ask for support if needed).
