### ISSUE TITLE
Can not downloade correct volume

### ISSUE THREAD

**Issue by greatlord** [gvellut/jncep#24]
Hi
download only part-4-volume 9 part 1 to 5 is not posible it split on wrong part-
the name is /ascendance-of-a-bookworm-part-4- then then volume and part comes
https://j-novel.club/read/ascendance-of-a-bookworm-part-4-volume-9-part-1

**Comment by gvellut** [comment]
- What files do you expect to download?
- What exact command are you running? 
- What files do you get?

**Comment by greatlord** [comment]
I want download as epub volume 9 with part 1 to 5 
but i get complete diffent volume and part i did try with  --parts 9

--parts 9
Ascendance_of_a_Bookworm_Part_3_Volume_2_Part_1.epub'
not 
ascendance-of-a-bookworm-part-4-volume-9-part-1 to part 5

**Comment by gvellut** [comment]
That is because "AoaB Part 4 Volume 9"  is actually volume **21** from the point of view of J-Novel Club. In the J-Novel Club API (and JNCEP as well), there are only 2 levels of organization for a specific series: Volume then Part, not 3 like the titles of the AoaB books would seem to indicate i.e. Part then Volume then Part again.

So you need to use `--parts 21`.

To get the volume number, you can go the AoaB series page on the J-Novel Club website then click on the title of the volume you want: For "AoaB Part 4 Volume 9", you will get the URL : `https://j-novel.club/series/ascendance-of-a-bookworm#volume-21` => so volume 21. You can also use that URL as argument to the `jncep epub` command in order to download all the parts of the volume (without using the `--parts` option).

**Comment by greatlord** [comment]
Thanks for you expain did it go on the name ascendance-of-a-bookworm-part-4-volume-9 it was volume 9
Can you update the readme or the help options to expain how the volume is counted so other people like me do not make this mistake again 

and thanks for all you help and support
I like you program allot

**Comment by gvellut** [comment]
OK. Good idea. I will add a note in the documentation.
