### ISSUE TITLE
jncep update constantly updates the same part

### ISSUE THREAD

**Issue by jzkmath** [gvellut/jncep#28]
**Describe the bug**
So this is probably an edge case but whenever I run ``jncep update`` the series "Realist Hero" always updates despite the latest part already updated. This is probably because j-novel club released a crossover story and it is listed as volume 18. So basically volume 17 has 11 out of 12 parts out then there is 1 part for "volume 18". I suspect that the unreleased part 12 is causing this issue.

**Expected behavior**
the update command shouldn't update a part that was already updated.

**To Reproduce**
run ``jncep update`` while tracking realist hero. Every time you run this command it will update volume 17 part 11. I expect this bug will disappear as soon as the last prepub part is released (this thursday i think)

**Debug trace**
N/A

**Environment:**
 - OS: Ubuntu 22.04
 - Python version: 3.10.36
 - JNCEP version: v38 (latest version as of writing report)

**Comment by gvellut** [comment]
OK I will have a look. `jncep `uses the release dates (to deal with the case you mention).

Could you send me your `track.json` file? It should be inside the `~/.jncep` folder.

**Comment by gvellut** [comment]
Actually, no need for your `track.json`. I can reproduce the issue even if I just subscribed to the series.

**Comment by gvellut** [comment]
I have made a correction. I will make a new release soon.

**Comment by jzkmath** [comment]
This might not be of much use to you but I did originally try un-tracking
then tracking again to see if it would solve the issue but it didn't
change anything.

**Comment by gvellut** [comment]
This is because the date of the last part (in number, so the date of 18.1 in this case) is recorded instead of the last date (ie date of 17.11) : The date of 18.1 is before the date of 17.11, hence the issue. 

But your message made me think: I forgot to apply the correction I did for the `update` (from your original issue) to the `track add` command (so the date of the last part is recorded). I will have to make another release for that...
