### ISSUE TITLE
Purchased parts don't get included as content

### ISSUE THREAD

**Issue by sh1mmer** [gvellut/jncep#38]
**Describe the bug**
For volumes I've bought the non-preview parts don't get included in any ebooks.

**Expected behavior**
All available parts end up in ebooks

**Comments**
I looked at the API metadata JSON for the series and it looks like there is no flag for purchased parts in the API response on the parts themselves. That said there is this flag on each volume `"owned": true,`. I'll try and make a PR but I think there are 2 approaches that could work:
1) just download the epub for owned books (might be preferable since the premium ebooks might have more art etc)
2) look for the `owned` flag on a volume and then mark all the parts as available in the filter somehow

**Comment by gvellut** [comment]
Thank you for your feedback.

I don't buy ebooks from J-Novel Club (I am simply a subscriber) so handling owned books have not been a focus for me but I am not opposed to make it better supported. I just wonder if there is really a use case for it: If you own the final ePub, is there a point in downloading it through the individual parts using jncep? Or maybe, you can pre-buy the ePub and download the prepubs in the meantime before the actual release? In that case, it would make sense.

Of the 2 options you outline: 
- the simplest would be option 2 since it would be an additional filter with little change that I can see. If you agree, I would prefer that you start with that one.
- the first option would mean calling another part of the JNC API. I think it should also be restricted to work when a whole volume is requested (otherwise, download only the individual parts). If I recall correctly, I saw in the JNC forums some script that allow to download owned ebooks. I guess the functionality could be borrowed from there:
   - An independent jncep subcommand to list and download owned ebooks 
   - \+ some way to detect a volume is owned and download that final ebook (instead of downloading and pasting together the individual prepub parts), when a whole volume is requested using the existing `jncep epub `command
     - (+ an option to trigger or disable that behaviour)

**Comment by sh1mmer** [comment]
I got the premium sub a while ago when I wanted to finish a giant catchup series I couldn't finish in a month. I think mostly since this is a nice tool for syncing it would be good to be able to grab all the ebooks available not just the free ones.

When I get time I'll come up with a PR starting with option 2, and then possibly look for a way to get any premium ebooks.

**Comment by gvellut** [comment]
I have added a check for owned volumes so the prepub parts can be included in the generated EPUB (ie the option 2 you mentioned above). It will be avaialble in the next jncep version. So I am closing this issue as completed for now.

If you feel like implementing the option 1, let me know and I will reopen this issue.
